repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    # -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.7.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
    -   id: docformatter
        args: ['--in-place', '--black', '--wrap-summaries=88', '--wrap-descriptions=88']
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.286
    hooks:
    -   id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
